" Setting up Vim Plug
"
" curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
"
" Then in vim run
" :PlugInstall
"
"
call plug#begin('~/.vim/plugged')

" Cosmetic Plugins

Plug 'sjl/badwolf'                    " A nice color palette
Plug 'tpope/vim-sensible'             " Recommended defaults
Plug 'vim-airline/vim-airline'        " A nice status line
Plug 'vim-airline/vim-airline-themes' " Status line themes

" IDE Emulation

Plug 'tpope/vim-repeat'             " Smart repeating
Plug 'tpope/vim-surround'           " Paren edits
Plug 'tpope/vim-commentary'         " Block comments
Plug 'junegunn/vim-easy-align'      " Alingment

call plug#end()

colorscheme badwolf
let g:airline_theme='badwolf'

set number
set relativenumber

set expandtab    " On pressing tab, insert 4 spaces
set tabstop=4    " show existing tab with 4 spaces width
set shiftwidth=4 " when indenting with '>', use 4 spaces width
set softtabstop=4
set smartindent

set nohlsearch
set incsearch

set nowrap

set termguicolors

set scrolloff=4

let g:netrw_banner = 0
let g:netrw_liststyle = 3
